# Generated by Django 5.1.1 on 2024-10-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('placa', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('marca', models.CharField(default='', max_length=50)),
                ('modelo', models.CharField(default='', max_length=50)),
                ('ano', models.IntegerField(default=0)),
                ('cor', models.CharField(default='', max_length=20)),
                ('quilometragem', models.IntegerField(default=0)),
                ('combustivel', models.CharField(choices=[('gasolina', 'Gasolina'), ('etanol', 'Etanol'), ('diesel', 'Diesel'), ('eletrico', 'Elétrico'), ('hibrido', 'Híbrido')], default='gasolina', max_length=20)),
                ('proprietario', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
